; draft-ietf-core-coral-03

document = [*element]

element = link / form / directive

directive = base-directive

base-directive = [1, baseURI]

baseURI = CRI-Reference

IRI = CRI-Reference

link = [2, relation-type, link-target, ?[*element]]

relation-type = IRI

link-target = IRI / literal / null

literal = bool / int / float / time / bytes / text

form = [3, operation-type, submission-target, ?[*form-field]]

operation-type = IRI

submission-target = IRI

form-field = (form-field-type, form-field-value, ?[*element])

form-field-type = IRI

form-field-value = IRI / literal / null

relation-type /= uint
link-target /= #6.6(uint)
operation-type /= uint
submission-target /= #6.6(uint)
form-field-type /= uint
form-field-value /= #6.6(uint)

CoRAL-Document = document
CoRAL-Link = link
CoRAL-Form = form

CRI-Reference = [
  (?scheme, ?((host.name // host.ip), ?port) // path.type),
  *path,
  *query,
  ?fragment
]

scheme    = (0, text .regexp "[a-z][a-z0-9+.-]*")
host.name = (1, text)
host.ip   = (2, bytes .size 4 / bytes .size 16)
port      = (3, 0..65535)
path.type = (4, 0..127)
path      = (5, text)
query     = (6, text)
fragment  = (7, text)
